// ARENA XI — base de dados dos clubes (temporada 2026/27)
// Técnicos e elencos refletem a posição mais recente conhecida; podem sofrer
// pequenas mudanças pontuais ao longo da temporada (transferências, demissões).
const TEAMS = [

/* ===================== PREMIER LEAGUE (Inglaterra) ===================== */
{id:'arsenal', name:'Arsenal', league:'premier', country:'Inglaterra', city:'Londres', founded:1886, stadium:'Emirates Stadium', coach:'Mikel Arteta', color:'#EF0107',
 titles:['13x Campeão inglês','14x FA Cup','Campeão da Premier League 2025/26'],
 legends:['Thierry Henry','Dennis Bergkamp','Tony Adams'],
 squad:['Bukayo Saka','Declan Rice','Martin Ødegaard','William Saliba','David Raya'],
 formation:'4-3-3', lines:[['Raya'],['White','Saliba','Gabriel','Calafiori'],['Rice','Ødegaard','Merino'],['Saka','Havertz','Martinelli']]},

{id:'aston-villa', name:'Aston Villa', league:'premier', country:'Inglaterra', city:'Birmingham', founded:1874, stadium:'Villa Park', coach:'Unai Emery', color:'#95BFE5',
 titles:['7x Campeão inglês','1x Copa dos Campeões da Europa (1982)'],
 legends:['Peter Withe','Paul McGrath','Gareth Southgate'],
 squad:['Emiliano Martínez','Ollie Watkins','Youri Tielemans','Morgan Rogers'],
 formation:'4-2-3-1', lines:[['Martínez'],['Cash','Konsa','Torres','Digne'],['Onana','Tielemans'],['Rogers','McGinn','Bailey'],['Watkins']]},

{id:'bournemouth', name:'AFC Bournemouth', league:'premier', country:'Inglaterra', city:'Bournemouth', founded:1899, stadium:'Vitality Stadium', coach:'Andoni Iraola', color:'#DA291C',
 titles:['1ª qualificação europeia da história do clube (2026/27)'],
 legends:['Steve Fletcher'],
 squad:['Antoine Semenyo','Marcos Senesi','Illia Zabarnyi','Djordje Petrović'],
 formation:'4-2-3-1', lines:[['Petrović'],['Smith','Senesi','Zabarnyi','Kerkez'],['Cook','Christie'],['Semenyo','Kluivert','Brooks'],['Evanilson']]},

{id:'brentford', name:'Brentford', league:'premier', country:'Inglaterra', city:'Londres', founded:1889, stadium:'Gtech Community Stadium', coach:'Keith Andrews', color:'#E30613',
 titles:['Conhecido pelo modelo de análise de dados e formação de jogadores'],
 legends:['Ivan Toney'],
 squad:['Kevin Schade','Nathan Collins','Yehor Yarmoliuk','Mark Flekken'],
 formation:'3-5-2', lines:[['Flekken'],['Collins','Pinnock','Ajer'],['Roerslev','Nørgaard','Janelt','Yarmoliuk','Ghoddos'],['Schade','Damsgaard']]},

{id:'brighton', name:'Brighton & Hove Albion', league:'premier', country:'Inglaterra', city:'Brighton', founded:1901, stadium:'American Express Stadium', coach:'Fabian Hürzeler', color:'#0057B8',
 titles:['Referência europeia em scouting e revenda de jogadores'],
 legends:['Glenn Murray'],
 squad:['Kaoru Mitoma','Georginio Rutter','Bart Verbruggen','Jan Paul van Hecke'],
 formation:'4-2-3-1', lines:[['Verbruggen'],['Veltman','van Hecke','Dunk','Estupiñán'],['Baleba','Ayari'],['Mitoma','Rutter','Minteh'],['Welbeck']]},

{id:'chelsea', name:'Chelsea', league:'premier', country:'Inglaterra', city:'Londres', founded:1905, stadium:'Stamford Bridge', coach:'Enzo Maresca', color:'#034694',
 titles:['6x Campeão inglês','2x Champions League (2012, 2021)','Campeão Mundial de Clubes 2025'],
 legends:['Frank Lampard','John Terry','Didier Drogba'],
 squad:['Cole Palmer','Enzo Fernández','Moisés Caicedo','Robert Sánchez'],
 formation:'4-2-3-1', lines:[['Sánchez'],['James','Colwill','Fofana','Cucurella'],['Caicedo','Fernández'],['Palmer','Nkunku','Neto'],['Jackson']]},

{id:'coventry', name:'Coventry City', league:'premier', country:'Inglaterra', city:'Coventry', founded:1883, stadium:'CBS Arena', coach:'Frank Lampard', color:'#78D0F1',
 titles:['1x FA Cup (1987)','Acesso à Premier League após 25 anos fora da elite'],
 legends:['Dion Dublin'],
 squad:['Ellis Simms','Haji Wright','Ben Sheaf','Jack Rudoni'],
 formation:'4-2-3-1', lines:[['Wollacott'],['Bidwell','McFadzean','Hyam','Sakamoto'],['Sheaf','Godden'],['Rudoni','Wright','Torp'],['Simms']]},

{id:'crystal-palace', name:'Crystal Palace', league:'premier', country:'Inglaterra', city:'Londres', founded:1905, stadium:'Selhurst Park', coach:'Oliver Glasner', color:'#1B458F',
 titles:['1x FA Cup (2024/25)','Campeão da Community Shield 2025'],
 legends:['Ian Wright'],
 squad:['Eberechi Eze','Jean-Philippe Mateta','Marc Guéhi','Dean Henderson'],
 formation:'3-4-3', lines:[['Henderson'],['Guéhi','Andersen','Mitchell'],['Munoz','Hughes','Wharton','Lerma'],['Eze','Mateta','Sarr']]},

{id:'everton', name:'Everton', league:'premier', country:'Inglaterra', city:'Liverpool', founded:1878, stadium:'Estádio Hill Dickinson (Bramley-Moore Dock)', coach:'David Moyes', color:'#003399',
 titles:['9x Campeão inglês','5x FA Cup'],
 legends:['Dixie Dean','Alan Ball','Duncan Ferguson'],
 squad:['Jordan Pickford','Dwight McNeil','Jack Grealish','Iliman Ndiaye'],
 formation:'4-2-3-1', lines:[['Pickford'],['O\'Brien','Keane','Tarkowski','Mykolenko'],['Gueye','Garner'],['McNeil','Grealish','Ndiaye'],['Beto']]},

{id:'fulham', name:'Fulham', league:'premier', country:'Inglaterra', city:'Londres', founded:1879, stadium:'Craven Cottage', coach:'Marco Silva', color:'#000000',
 titles:['Clube mais antigo de Londres na elite'],
 legends:['Johnny Haynes'],
 squad:['Alex Iwobi','Emile Smith Rowe','Sasa Lukic','Bernd Leno'],
 formation:'4-2-3-1', lines:[['Leno'],['Robinson','Diop','Bassey','Castagne'],['Sander Berge','Lukic'],['Iwobi','Smith Rowe','Wilson'],['Jiménez']]},

{id:'hull-city', name:'Hull City', league:'premier', country:'Inglaterra', city:'Hull', founded:1904, stadium:'MKM Stadium', coach:'Sergio Rico? (a confirmar)', color:'#F18A00',
 titles:['Acesso à Premier League via playoffs em 2026'],
 legends:['Dean Windass'],
 squad:['Jaden Philogene','Ryan Giles','Liam Delap Jr.? (exemplo)'],
 formation:'4-2-3-1', lines:[['Ingram'],['Coyle','Jones','McLoughlin','Giles'],['Seri','Slater'],['Philogene','Traoré','Longman'],['Simons']]},

{id:'ipswich', name:'Ipswich Town', league:'premier', country:'Inglaterra', city:'Ipswich', founded:1878, stadium:'Portman Road', coach:'Kieran McKenna', color:'#0044A9',
 titles:['1x Título inglês (1961/62)','1x Copa da UEFA (1981)'],
 legends:['Kevin Beattie','Sir Bobby Robson (técnico histórico)'],
 squad:['Liam Delap','Omari Hutchinson','Sam Morsy','Arijanet Muric'],
 formation:'4-2-3-1', lines:[['Muric'],['Burns','Greaves','Woolfenden','Davis'],['Morsy','Cajuste'],['Hutchinson','Szmodics','Chaplin'],['Delap']]},

{id:'leeds', name:'Leeds United', league:'premier', country:'Inglaterra', city:'Leeds', founded:1919, stadium:'Elland Road', coach:'Daniel Farke', color:'#FFCD00',
 titles:['3x Campeão inglês','1x Copa das Feiras (Inter-Cities Fairs Cup)'],
 legends:['Billy Bremner','Don Revie (técnico histórico)'],
 squad:['Daniel James','Joel Piroe','Ethan Ampadu','Illan Meslier'],
 formation:'4-2-3-1', lines:[['Meslier'],['Ayling','Rodon','Cooper','Gray'],['Ampadu','Gruev'],['James','Piroe','Gnonto'],['Rutter']]},

{id:'liverpool', name:'Liverpool', league:'premier', country:'Inglaterra', city:'Liverpool', founded:1892, stadium:'Anfield', coach:'Arne Slot', color:'#C8102E',
 titles:['6x Champions League','19x Campeão inglês','8x FA Cup'],
 legends:['Steven Gerrard','Kenny Dalglish','Mohamed Salah'],
 squad:['Mohamed Salah','Virgil van Dijk','Alisson','Alexis Mac Allister'],
 formation:'4-3-3', lines:[['Alisson'],['Alexander-Arnold','Van Dijk','Konaté','Robertson'],['Mac Allister','Gravenberch','Szoboszlai'],['Salah','Núñez','Díaz']]},

{id:'man-city', name:'Manchester City', league:'premier', country:'Inglaterra', city:'Manchester', founded:1880, stadium:'Etihad Stadium', coach:'Pep Guardiola', color:'#6CABDD',
 titles:['1x Champions League (2023)','10x Premier League','7x FA Cup'],
 legends:['Sergio Agüero','David Silva','Vincent Kompany'],
 squad:['Erling Haaland','Rodri','Phil Foden','Ederson'],
 formation:'4-2-3-1', lines:[['Ederson'],['Gvardiol','Dias','Stones','Walker'],['Rodri','Gündoğan'],['Doku','Foden','Savinho'],['Haaland']]},

{id:'man-united', name:'Manchester United', league:'premier', country:'Inglaterra', city:'Manchester', founded:1878, stadium:'Old Trafford', coach:'Rúben Amorim', color:'#DA020E',
 titles:['3x Champions League/Copa dos Campeões','20x Campeão inglês','13x FA Cup'],
 legends:['Sir Bobby Charlton','Ryan Giggs','Cristiano Ronaldo'],
 squad:['Bruno Fernandes','Bryan Mbeumo','Rasmus Højlund','André Onana'],
 formation:'3-4-3', lines:[['Onana'],['Yoro','Maguire','de Ligt'],['Dalot','Mainoo','Ugarte','Dorgu'],['Mbeumo','Højlund','B. Fernandes']]},

{id:'newcastle', name:'Newcastle United', league:'premier', country:'Inglaterra', city:'Newcastle upon Tyne', founded:1892, stadium:'St James\' Park', coach:'Eddie Howe', color:'#241F20',
 titles:['4x Campeão inglês (era pré-Premier)','1x Copa da Liga Inglesa (2024/25)'],
 legends:['Alan Shearer','Kevin Keegan'],
 squad:['Alexander Isak','Anthony Gordon','Bruno Guimarães','Nick Pope'],
 formation:'4-3-3', lines:[['Pope'],['Livramento','Botman','Schär','Burn'],['Guimarães','Tonali','Longstaff'],['Gordon','Isak','Barnes']]},

{id:'nottingham-forest', name:'Nottingham Forest', league:'premier', country:'Inglaterra', city:'Nottingham', founded:1865, stadium:'City Ground', coach:'Ange Postecoglou', color:'#DD0000',
 titles:['2x Copa dos Campeões da Europa (1979, 1980)','1x Campeão inglês (1978)'],
 legends:['Stuart Pearce','Brian Clough (técnico histórico)'],
 squad:['Chris Wood','Morgan Gibbs-White','Murillo','Matz Sels'],
 formation:'4-2-3-1', lines:[['Sels'],['Aina','Murillo','Milenković','Williams'],['Yates','Anderson'],['Gibbs-White','Elanga','Sangaré'],['Wood']]},

{id:'sunderland', name:'Sunderland', league:'premier', country:'Inglaterra', city:'Sunderland', founded:1879, stadium:'Stadium of Light', coach:'Régis Le Bris', color:'#EB172B',
 titles:['6x Campeão inglês (era histórica)','2x FA Cup'],
 legends:['Charlie Hurley','Kevin Phillips'],
 squad:['Wilson Isidor','Chris Rigg','Granit Xhaka','Anthony Patterson'],
 formation:'4-2-3-1', lines:[['Patterson'],['Hume','Ballard','Alderete','Vitinho'],['Xhaka','Sadiki'],['Le Fée','Rigg','Roberts'],['Isidor']]},

{id:'tottenham', name:'Tottenham Hotspur', league:'premier', country:'Inglaterra', city:'Londres', founded:1882, stadium:'Tottenham Hotspur Stadium', coach:'Thomas Frank', color:'#132257',
 titles:['1x Europa League (2024/25)','2x Campeão inglês','8x FA Cup'],
 legends:['Harry Kane','Gary Lineker','Ledley King'],
 squad:['James Maddison','Dominic Solanke','Micky van de Ven','Guglielmo Vicario'],
 formation:'4-2-3-1', lines:[['Vicario'],['Porro','Van de Ven','Romero','Udogie'],['Bissouma','Bentancur'],['Maddison','Kulusevski','Johnson'],['Solanke']]},

/* ===================== LA LIGA (Espanha) ===================== */
{id:'athletic-club', name:'Athletic Club', league:'laliga', country:'Espanha', city:'Bilbao', founded:1898, stadium:'San Mamés', coach:'Ernesto Valverde', color:'#EE2E24',
 titles:['8x La Liga','24x Copa do Rei'],
 legends:['Telmo Zarra','Fernando Llorente'],
 squad:['Nico Williams','Iñaki Williams','Unai Simón','Óscar de Marcos'],
 formation:'4-2-3-1', lines:[['Simón'],['De Marcos','Paredes','Vivian','Berchiche'],['Vesga','Galarreta'],['N. Williams','Sancet','Berenguer'],['Guruzeta']]},

{id:'atletico-madrid', name:'Atlético de Madrid', league:'laliga', country:'Espanha', city:'Madri', founded:1903, stadium:'Riyadh Air Metropolitano', coach:'Diego Simeone', color:'#CB3524',
 titles:['11x La Liga','10x Copa do Rei'],
 legends:['Fernando Torres','Koke','Antoine Griezmann'],
 squad:['Julián Álvarez','Antoine Griezmann','Koke','Jan Oblak'],
 formation:'4-4-2', lines:[['Oblak'],['Molina','Giménez','Witsel','Galán'],['Koke','Barrios','De Paul','Llorente'],['Álvarez','Griezmann']]},

{id:'osasuna', name:'CA Osasuna', league:'laliga', country:'Espanha', city:'Pamplona', founded:1920, stadium:'El Sadar', coach:'Vicente Moreno', color:'#D2001F',
 titles:['2x Copa do Rei (finalista recorrente)'],
 legends:['Julio César Cámara'],
 squad:['Ante Budimir','Rubén García','Aimar Oroz'],
 formation:'4-4-2', lines:[['Herrera'],['Boyomo','Catena','Cruz','Areso'],['García','Torró','Oroz','Moncayola'],['Budimir','Bryan Zaragoza']]},

{id:'celta', name:'Celta de Vigo', league:'laliga', country:'Espanha', city:'Vigo', founded:1923, stadium:'Balaídos', coach:'Claudio Giráldez', color:'#8AC3EE',
 titles:['1x Copa da Espanha (1948, como Celta)'],
 legends:['Iago Aspas'],
 squad:['Iago Aspas','Borja Iglesias','Fran Beltrán'],
 formation:'4-2-3-1', lines:[['Iván Villar'],['Mingueza','Starfelt','Núñez','Álvarez'],['Beltrán','Sotelo'],['Aspas','Iglesias','Bamba'],['Douvikas']]},

{id:'alaves', name:'Deportivo Alavés', league:'laliga', country:'Espanha', city:'Vitória-Gasteiz', founded:1921, stadium:'Mendizorrotza', coach:'Eduardo Coudet', color:'#0055A4',
 titles:['Tradicional clube basco de meio de tabela'],
 legends:['Ibon Begoña'],
 squad:['Kike García','Toni Martínez','Jon Guridi'],
 formation:'4-2-3-1', lines:[['Sivera'],['Fernández','Abqar','Tenaglia','Toni'],['Guridi','Guevara'],['Rebbach','Vicente','García'],['Boyé']]},

{id:'elche', name:'Elche CF', league:'laliga', country:'Espanha', city:'Elche', founded:1923, stadium:'Estadio Manuel Martínez Valero', coach:'Eder Sarabia', color:'#00843D',
 titles:['Clube historicamente de meio de tabela na La Liga'],
 legends:['Rubén Baraja (ex-jogador e técnico)'],
 squad:['Rafa Mir','André Silva','Federico Redondo'],
 formation:'4-4-2', lines:[['Iñaki Peña'],['Chust','Sánchez','Gumbau','Diego González'],['Aguado','Redondo','Nieto','Mir'],['Bouzas','A. Silva']]},

{id:'barcelona', name:'FC Barcelona', league:'laliga', country:'Espanha', city:'Barcelona', founded:1899, stadium:'Spotify Camp Nou', coach:'Hansi Flick', color:'#A50044',
 titles:['5x Champions League','29x La Liga','31x Copa do Rei'],
 legends:['Lionel Messi','Johan Cruyff','Ronaldinho'],
 squad:['Lamine Yamal','Robert Lewandowski','Pedri','Raphinha'],
 formation:'4-3-3', lines:[['Ter Stegen'],['Balde','Koundé','Araújo','Kounde'],['De Jong','Pedri','Gavi'],['Raphinha','Lewandowski','Yamal']]},

{id:'getafe', name:'Getafe CF', league:'laliga', country:'Espanha', city:'Getafe (Madri)', founded:1946, stadium:'Coliseum', coach:'José Bordalás', color:'#0067B1',
 titles:['Conhecido pelo estilo de jogo físico e competitivo'],
 legends:['Juan Valerón'],
 squad:['Borja Mayoral','Mauro Arambarri','David Soria'],
 formation:'4-4-2', lines:[['Soria'],['Rico','Djené','Domingos','Duarte'],['Arambarri','Milla','Arambarri','Álex'],['Mayoral','Uche']]},

{id:'levante', name:'Levante UD', league:'laliga', country:'Espanha', city:'Valência', founded:1909, stadium:'Estadi Ciutat de València', coach:'Julián Calero', color:'#00205B',
 titles:['1x Copa Catalunha'],
 legends:['David Barral'],
 squad:['Iván Romero','José Luis Morales','Carlos Álvarez'],
 formation:'4-3-3', lines:[['Dani Cárdenas'],['Toljan','Cabello','Ponce','Ekhator'],['Romero','Pablo Martínez','Álvarez'],['Morales','Etta Eyong','Kervin Arriaga']]},

{id:'malaga', name:'Málaga CF', league:'laliga', country:'Espanha', city:'Málaga', founded:1904, stadium:'La Rosaleda', coach:'Sergio Pellicer', color:'#0057A8',
 titles:['Quartas de final da Champions League 2012/13'],
 legends:['Julio Baptista','Isco (formado no clube)'],
 squad:['Roque Mesa','Dioni Villalba','Adrián Niño'],
 formation:'4-2-3-1', lines:[['Andrés Fernández'],['Kevin','Rodríguez','Chavarría','Roberto'],['Mesa','Aguado'],['Dioni','Larrubia','Genaro'],['Niño']]},

{id:'r-racing', name:'Racing Santander', league:'laliga', country:'Espanha', city:'Santander', founded:1913, stadium:'El Sardinero', coach:'José Alberto', color:'#00A651',
 titles:['Retorno à La Liga após 14 anos de ausência'],
 legends:['Pedro Munitis'],
 squad:['Íñigo Vicente','Andrés Martín','Álvaro Mantilla'],
 formation:'4-4-2', lines:[['Broche'],['Aldasoro','Mantilla','Kike','Marlon'],['Vallejo','Suleiman','Villalibre','Andrés'],['Vicente','Petrusic']]},

{id:'rayo-vallecano', name:'Rayo Vallecano', league:'laliga', country:'Espanha', city:'Madri', founded:1924, stadium:'Estadio de Vallecas', coach:'Íñigo Pérez', color:'#E30022',
 titles:['Clube popular do bairro operário de Vallecas em Madri'],
 legends:['Míchel (ex-jogador e técnico)'],
 squad:['Isi Palazón','Álvaro García','Randy Nteka'],
 formation:'4-2-3-1', lines:[['Batalla'],['Balliu','Lejeune','Ratiu','Ciss'],['Valentín','Pathé'],['Palazón','Nteka','García'],['Camello']]},

{id:'rc-deportivo', name:'RC Deportivo (La Coruña)', league:'laliga', country:'Espanha', city:'A Coruña', founded:1906, stadium:'Riazor', coach:'Antonio Hidalgo', color:'#005CA9',
 titles:['1x La Liga (1999/2000)','2x Copa do Rei'],
 legends:['Fran','Bebeto','Djalminha'],
 squad:['Yeremay Hernández','Yeboah','Lucas Pérez'],
 formation:'4-3-3', lines:[['Germán Parreño'],['Barcia','Loureiro','Bakis','Ximo'],['Villares','Mella','Yeboah'],['Yeremay','Lucas Pérez','Iglesias']]},

{id:'espanyol', name:'RCD Espanyol', league:'laliga', country:'Espanha', city:'Barcelona', founded:1900, stadium:'RCDE Stadium', coach:'Manolo González', color:'#004A93',
 titles:['4x Copa do Rei'],
 legends:['Raúl Tamudo'],
 squad:['Javi Puado','Pere Milla','Joan García'],
 formation:'4-2-3-1', lines:[['J. García'],['Tejero','Calero','El Hilali','Pedrosa'],['Urko','Expósito'],['Puado','Milla','Kike'],['Roca']]},

{id:'real-betis', name:'Real Betis', league:'laliga', country:'Espanha', city:'Sevilha', founded:1907, stadium:'Estadio Benito Villamarín', coach:'Manuel Pellegrini', color:'#00954C',
 titles:['1x La Liga (1934/35)','3x Copa do Rei'],
 legends:['Joaquín Sánchez','Rafael Gordillo'],
 squad:['Isco','Vitor Roque','Marc Bartra','Adrián San Miguel'],
 formation:'4-2-3-1', lines:[['Adrián'],['Ricardo','Bartra','Natan','Miranda'],['Fornals','Pablo Fornals'],['Isco','Ezzalzouli','Antony'],['Vitor Roque']]},

{id:'real-madrid', name:'Real Madrid', league:'laliga', country:'Espanha', city:'Madri', founded:1902, stadium:'Santiago Bernabéu', coach:'Xabi Alonso', color:'#FEBE10',
 titles:['15x Champions League','36x La Liga','20x Copa do Rei'],
 legends:['Alfredo Di Stéfano','Raúl','Cristiano Ronaldo'],
 squad:['Kylian Mbappé','Jude Bellingham','Vinícius Júnior','Thibaut Courtois'],
 formation:'4-3-3', lines:[['Courtois'],['Alaba','Carvajal','Militão','Mendy'],['Tchouaméni','Bellingham','Camavinga'],['Vini Jr.','Mbappé','Rodrygo']]},

{id:'real-sociedad', name:'Real Sociedad', league:'laliga', country:'Espanha', city:'San Sebastián', founded:1909, stadium:'Reale Arena', coach:'Sergio Francisco', color:'#0058A9',
 titles:['2x La Liga','3x Copa do Rei'],
 legends:['Xabi Alonso (ex-jogador)','Mikel Arteta (ex-jogador)'],
 squad:['Mikel Oyarzabal','Take Kubo','Ander Barrenetxea'],
 formation:'4-2-3-1', lines:[['Remiro'],['Aihen','Zubeldia','Aramburu','Odriozola'],['Zubimendi','Sucic'],['Kubo','Oyarzabal','Barrenetxea'],['Sadiq']]},

{id:'sevilla', name:'Sevilla FC', league:'laliga', country:'Espanha', city:'Sevilha', founded:1890, stadium:'Ramón Sánchez-Pizjuán', coach:'Matías Almeyda', color:'#D0021B',
 titles:['7x Europa League/Copa da UEFA','1x La Liga (1945/46)'],
 legends:['Jesús Navas','Sergio Ramos'],
 squad:['Isaac Romero','Chidera Ejuke','Marcao'],
 formation:'4-2-3-1', lines:[['Vlachodimos'],['Carmona','Marcão','Pedrosa','Ramos'],['Sow','Agoumé'],['Ejuke','Almeida','Sánchez'],['Romero']]},

{id:'valencia', name:'Valencia CF', league:'laliga', country:'Espanha', city:'Valência', founded:1919, stadium:'Estadio de Mestalla', coach:'Carlos Corberán', color:'#EE3524',
 titles:['6x La Liga','8x Copa do Rei'],
 legends:['David Villa','Mario Kempes'],
 squad:['Hugo Duro','Diego López','Javi Guerra'],
 formation:'4-4-2', lines:[['Mamardashvili'],['Foulquier','Tárrega','Diakhaby','Gayà'],['Guerra','Pepelu','López','Rioja'],['Duro','Danjuma']]},

{id:'villarreal', name:'Villarreal CF', league:'laliga', country:'Espanha', city:'Villarreal', founded:1923, stadium:'Estadio de la Cerámica', coach:'Marcelino García Toral', color:'#FFE667',
 titles:['1x Conference League (2020/21, como Europa League)'],
 legends:['Juan Román Riquelme (ex-jogador)','Santi Cazorla'],
 squad:['Ayoze Pérez','Gerard Moreno','Dani Parejo'],
 formation:'4-4-2', lines:[['Luiz Júnior'],['Kambwala','Foyth','Cardona','Pedraza'],['Parejo','Comesaña','Pape Gueye','Yeremy'],['Ayoze','G. Moreno']]},

/* ===================== SERIE A (Itália) ===================== */
{id:'atalanta', name:'Atalanta', league:'seriea', country:'Itália', city:'Bergamo', founded:1907, stadium:'Gewiss Stadium', coach:'Ivan Jurić', color:'#1E71B8',
 titles:['1x Europa League (2023/24)','1x Copa da Itália'],
 legends:['Alberto Bollini'],
 squad:['Ademola Lookman','Charles De Ketelaere','Mateo Retegui'],
 formation:'3-4-2-1', lines:[['Carnesecchi'],['Djimsiti','Hien','Kolasinac'],['Zappacosta','Éderson','De Roon','Ruggeri'],['Lookman','De Ketelaere'],['Retegui']]},

{id:'bologna', name:'Bologna', league:'seriea', country:'Itália', city:'Bolonha', founded:1909, stadium:'Stadio Renato Dall\'Ara', coach:'Vincenzo Italiano', color:'#8B0304',
 titles:['1x Copa da Itália (2024/25)','7x Campeão italiano (era histórica)'],
 legends:['Giacomo Bulgarelli'],
 squad:['Riccardo Orsolini','Santiago Castro','Lukas Skorupski'],
 formation:'4-2-3-1', lines:[['Skorupski'],['Holm','Beukema','Lucumí','Miranda'],['Freuler','Ferguson'],['Orsolini','Fabbian','Ndoye'],['Castro']]},

{id:'cagliari', name:'Cagliari', league:'seriea', country:'Itália', city:'Cagliari (Sardenha)', founded:1920, stadium:'Unipol Domus', coach:'Fabio Pisacane', color:'#B71234',
 titles:['1x Campeão italiano (1969/70)'],
 legends:['Gigi Riva'],
 squad:['Gianluca Lapadula','Nadir Zortea','Razvan Marin'],
 formation:'4-3-3', lines:[['Scuffet'],['Zappa','Mina','Luperto','Augello'],['Marin','Deiola','Adopo'],['Zortea','Lapadula','Luvumbo']]},

{id:'como', name:'Como 1907', league:'seriea', country:'Itália', city:'Como', founded:1907, stadium:'Stadio Giuseppe Sinigaglia', coach:'Cesc Fàbregas', color:'#0057A3',
 titles:['Retorno recente à elite italiana após décadas de ausência'],
 legends:['Cesc Fàbregas (técnico e ex-jogador)'],
 squad:['Nico Paz','Patrick Cutrone','Máximo Perrone'],
 formation:'4-3-3', lines:[['Butez'],['Van der Brempt','Dossena','Kempf','Valle'],['Perrone','Da Cunha','Paz'],['Diao','Cutrone','Addai']]},

{id:'cremonese', name:'Cremonese', league:'seriea', country:'Itália', city:'Cremona', founded:1903, stadium:'Stadio Giovanni Zini', coach:'Davide Nicola', color:'#909090',
 titles:['Acesso recente à Serie A via playoffs'],
 legends:['Gianluca Vialli (formado no clube)'],
 squad:['Federico Bonazzoli','Michele Collocolo'],
 formation:'3-5-2', lines:[['Audero'],['Bianchetti','Ceccherini','Lochoshvili'],['Zanimacchia','Vandeputte','Collocolo','Payero','Sernicola'],['Bonazzoli','Vazquez']]},

{id:'fiorentina', name:'Fiorentina', league:'seriea', country:'Itália', city:'Florença', founded:1926, stadium:'Stadio Artemio Franchi', coach:'Raffaele Palladino', color:'#582C83',
 titles:['2x Campeão italiano','6x Copa da Itália'],
 legends:['Gabriel Batistuta','Giancarlo Antognoni'],
 squad:['Moise Kean','Albert Guðmundsson','David De Gea'],
 formation:'4-2-3-1', lines:[['De Gea'],['Dodô','Ranieri','Comuzzo','Gosens'],['Mandragora','Fagioli'],['Guðmundsson','Bove','Sottil'],['Kean']]},

{id:'genoa', name:'Genoa', league:'seriea', country:'Itália', city:'Gênova', founded:1893, stadium:'Stadio Luigi Ferraris', coach:'Patrick Vieira', color:'#092451',
 titles:['9x Campeão italiano — clube mais antigo da Itália'],
 legends:['Renzo De Vecchi'],
 squad:['Andrea Pinamonti','Milan Badelj','Aaron Martín'],
 formation:'4-3-3', lines:[['Leali'],['Sabelli','Vasquez','Vogliacco','Martín'],['Frendrup','Masini','Badelj'],['Zanoli','Pinamonti','Ekhator']]},

{id:'hellas-verona', name:'Hellas Verona', league:'seriea', country:'Itália', city:'Verona', founded:1903, stadium:'Stadio Marcantonio Bentegodi', coach:'Paolo Zanetti', color:'#F2C230',
 titles:['1x Campeão italiano (1984/85)'],
 legends:['Preben Elkjær'],
 squad:['Tomás Suslov','Casper Tengstedt'],
 formation:'3-4-2-1', lines:[['Montipò'],['Coppola','Dawidowicz','Frese'],['Tchatchoua','Serdar','Duda','Bradarić'],['Suslov','Livramento'],['Tengstedt']]},

{id:'inter', name:'Inter de Milão', league:'seriea', country:'Itália', city:'Milão', founded:1908, stadium:'San Siro (Giuseppe Meazza)', coach:'Cristian Chivu', color:'#0068A8',
 titles:['3x Champions League/Copa dos Campeões','20x Serie A','9x Coppa Italia'],
 legends:['Javier Zanetti','Ronaldo Fenômeno','Giuseppe Meazza'],
 squad:['Lautaro Martínez','Nicolò Barella','Yann Sommer'],
 formation:'3-5-2', lines:[['Sommer'],['Bastoni','de Vrij','Acerbi'],['Dumfries','Barella','Çalhanoğlu','Dimarco'],['Lautaro','Thuram']]},

{id:'juventus', name:'Juventus', league:'seriea', country:'Itália', city:'Turim', founded:1897, stadium:'Allianz Stadium', coach:'Igor Tudor', color:'#000000',
 titles:['2x Champions League/Copa dos Campeões','36x Serie A','15x Coppa Italia'],
 legends:['Alessandro Del Piero','Gianluigi Buffon','Michel Platini'],
 squad:['Dušan Vlahović','Kenan Yıldız','Manuel Locatelli'],
 formation:'3-5-2', lines:[['Di Gregorio'],['Gatti','Kalulu','Kelly'],['Weah','Locatelli','Thuram','McKennie','Cambiaso'],['Vlahović','Yıldız']]},

{id:'lazio', name:'Lazio', league:'seriea', country:'Itália', city:'Roma', founded:1900, stadium:'Stadio Olimpico', coach:'Maurizio Sarri', color:'#87CEEB',
 titles:['2x Campeão italiano','8x Copa da Itália'],
 legends:['Alessandro Nesta','Pavel Nedvěd'],
 squad:['Mattia Zaccagni','Valentín Castellanos','Ivan Provedel'],
 formation:'4-3-3', lines:[['Provedel'],['Marusic','Gila','Romagnoli','Pellegrini'],['Rovella','Guendouzi','Dele-Bashiru'],['Zaccagni','Castellanos','Isaksen']]},

{id:'lecce', name:'Lecce', league:'seriea', country:'Itália', city:'Lecce', founded:1908, stadium:'Stadio Via del Mare', coach:'Marco Giampaolo', color:'#FFD400',
 titles:['Historicamente um clube consolidado do sul da Itália'],
 legends:['Giuseppe Signori (passagem marcante)'],
 squad:['Nikola Krstović','Antonino Gallo'],
 formation:'4-3-3', lines:[['Falcone'],['Gallo','Baschirotto','Jean','Guilbert'],['Coulibaly','Ramadani','Berisha'],['Pierret','Krstović','Sansone']]},

{id:'milan', name:'AC Milan', league:'seriea', country:'Itália', city:'Milão', founded:1899, stadium:'San Siro (Giuseppe Meazza)', coach:'Massimiliano Allegri', color:'#FB090B',
 titles:['7x Champions League/Copa dos Campeões','19x Serie A'],
 legends:['Paolo Maldini','Franco Baresi','Kaká'],
 squad:['Christian Pulišić','Rafael Leão','Mike Maignan'],
 formation:'4-2-3-1', lines:[['Maignan'],['Calabria','Tomori','Gabbia','Hernández'],['Fofana','Modrić'],['Pulišić','Leão','Chukwueze'],['Gimenez']]},

{id:'napoli', name:'Napoli', league:'seriea', country:'Itália', city:'Nápoles', founded:1926, stadium:'Stadio Diego Armando Maradona', coach:'Antonio Conte', color:'#1E71B8',
 titles:['4x Campeão italiano','1x Copa da UEFA'],
 legends:['Diego Maradona','Marek Hamšík'],
 squad:['Victor Osimhen','Khvicha Kvaratskhelia','Alex Meret'],
 formation:'4-3-3', lines:[['Meret'],['Di Lorenzo','Rrahmani','Buongiorno','Olivera'],['Lobotka','Anguissa','McTominay'],['Politano','Lukaku','Kvaratskhelia']]},

{id:'parma', name:'Parma', league:'seriea', country:'Itália', city:'Parma', founded:1913, stadium:'Stadio Ennio Tardini', coach:'Fabio Pecchia', color:'#FFCB05',
 titles:['1x Recopa Europeia','2x Copa da UEFA'],
 legends:['Gianfranco Zola','Hernán Crespo'],
 squad:['Ange-Yoan Bonny','Adrián Bernabé'],
 formation:'4-3-3', lines:[['Suzuki'],['Delprato','Balogh','Circati','Valeri'],['Bernabé','Sohm','Estévez'],['Man','Bonny','Cancellieri']]},

{id:'pisa', name:'Pisa', league:'seriea', country:'Itália', city:'Pisa', founded:1909, stadium:'Arena Garibaldi', coach:'Alberto Gilardino', color:'#004A9F',
 titles:['Acesso à Serie A após longa ausência da elite'],
 legends:['Christian Panucci (passagem na base)'],
 squad:['Marius Marin','M\'Bala Nzola'],
 formation:'4-3-1-2', lines:[['Semper'],['Calabresi','Canestrelli','Caracciolo','Angori'],['Marin','Aebischer','Piccinini'],['Tramoni'],['Nzola','Moreo']]},

{id:'roma', name:'AS Roma', league:'seriea', country:'Itália', city:'Roma', founded:1927, stadium:'Stadio Olimpico', coach:'Gian Piero Gasperini', color:'#8E1F2F',
 titles:['1x Europa Conference League (2021/22)','3x Campeão italiano'],
 legends:['Francesco Totti','Daniele De Rossi'],
 squad:['Paulo Dybala','Artem Dovbyk','Mile Svilar'],
 formation:'3-4-2-1', lines:[['Svilar'],['Mancini','Ndicka','Hermoso'],['Celik','Koné','Cristante','Angeliño'],['Dybala','Soulé'],['Dovbyk']]},

{id:'sassuolo', name:'Sassuolo', league:'seriea', country:'Itália', city:'Sassuolo', founded:1920, stadium:'Mapei Stadium', coach:'Fabio Grosso', color:'#00A650',
 titles:['Acesso recente de volta à Serie A'],
 legends:['Domenico Berardi'],
 squad:['Domenico Berardi','Armand Laurienté'],
 formation:'4-2-3-1', lines:[['Muric'],['Toljan','Erlic','Idzes','Doig'],['Boloca','Thorstvedt'],['Berardi','Laurienté','Volpato'],['Pinamonti']]},

{id:'torino', name:'Torino', league:'seriea', country:'Itália', city:'Turim', founded:1906, stadium:'Stadio Olimpico Grande Torino', coach:'Paolo Vanoli', color:'#881C1C',
 titles:['7x Campeão italiano (era do "Grande Torino")'],
 legends:['Valentino Mazzola'],
 squad:['Duván Zapata','Ché Adams','Vanja Milinković-Savić'],
 formation:'3-5-2', lines:[['Milinković-Savić'],['Coco','Masina','Maripán'],['Lazaro','Ricci','Tameze','Vojvoda'],['Zapata','Adams']]},

{id:'udinese', name:'Udinese', league:'seriea', country:'Itália', city:'Udine', founded:1896, stadium:'Bluenergy Stadium', coach:'Kosta Runjaić', color:'#000000',
 titles:['Conhecido pela tradição em revelar talentos sul-americanos'],
 legends:['Antonio Di Natale'],
 squad:['Lorenzo Lucca','Florian Thauvin'],
 formation:'3-5-2', lines:[['Okoye'],['Bijol','Kabasele','Solet'],['Zemura','Karlström','Lovric','Ehizibue','Zarraga'],['Lucca','Thauvin']]},

/* ===================== BUNDESLIGA (Alemanha) ===================== */
{id:'bayern', name:'Bayern de Munique', league:'bundesliga', country:'Alemanha', city:'Munique', founded:1900, stadium:'Allianz Arena', coach:'Vincent Kompany', color:'#DC052D',
 titles:['6x Champions League','34x Bundesliga','20x Copa da Alemanha'],
 legends:['Franz Beckenbauer','Gerd Müller','Philipp Lahm'],
 squad:['Harry Kane','Jamal Musiala','Manuel Neuer'],
 formation:'4-2-3-1', lines:[['Neuer'],['Davies','Upamecano','Dier','Laimer'],['Kimmich','Goretzka'],['Coman','Musiala','Gnabry'],['Kane']]},

{id:'dortmund', name:'Borussia Dortmund', league:'bundesliga', country:'Alemanha', city:'Dortmund', founded:1909, stadium:'Signal Iduna Park', coach:'Niko Kovač', color:'#FDE100',
 titles:['1x Champions League (1996/97)','8x Bundesliga','5x Copa da Alemanha'],
 legends:['Michael Zorc','Marco Reus','Matthias Sammer'],
 squad:['Karim Adeyemi','Serhou Guirassy','Gregor Kobel'],
 formation:'4-2-3-1', lines:[['Kobel'],['Bensebaini','Anton','Schlotterbeck','Ryerson'],['Nmecha','Groß'],['Adeyemi','Guirassy','Brandt']]},

{id:'leipzig', name:'RB Leipzig', league:'bundesliga', country:'Alemanha', city:'Leipzig', founded:2009, stadium:'Red Bull Arena', coach:'Ole Werner', color:'#DD0741',
 titles:['1x Copa da Alemanha (2022/23)'],
 legends:['Timo Werner (formado no clube)'],
 squad:['Benjamin Šeško','Xavi Simons','Christoph Baumgartner'],
 formation:'4-2-3-1', lines:[['Gulácsi'],['Klostermann','Orbán','Lukeba','Raum'],['Schlager','Kampl'],['Simons','Baumgartner','Openda'],['Šeško']]},

{id:'stuttgart', name:'VfB Stuttgart', league:'bundesliga', country:'Alemanha', city:'Stuttgart', founded:1893, stadium:'MHPArena', coach:'Sebastian Hoeneß', color:'#E30613',
 titles:['3x Bundesliga','1x Copa da Alemanha (2023/24)'],
 legends:['Jürgen Klinsmann (formado no clube)'],
 squad:['Deniz Undav','Chris Führich','Alexander Nübel'],
 formation:'4-2-3-1', lines:[['Nübel'],['Mittelstädt','Chabot','Rouault','Vagnoman'],['Karazor','Stiller'],['Führich','Undav','Leweling'],['Demirović']]},

{id:'hoffenheim', name:'TSG Hoffenheim', league:'bundesliga', country:'Alemanha', city:'Sinsheim', founded:1899, stadium:'PreZero Arena', coach:'Christian Ilzer', color:'#1C63B7',
 titles:['Estreou na Bundesliga em 2008 e vem se consolidando na elite'],
 legends:['Sandro Wagner (formado no clube)'],
 squad:['Andrej Kramarić','Grischa Prömel'],
 formation:'3-4-2-1', lines:[['Baumann'],['Akpoguma','Vogt','Beier'],['Angeliño','Prömel','Bülter','Kaderabek'],['Kramarić','Asllani'],['Bebou']]},

{id:'leverkusen', name:'Bayer Leverkusen', league:'bundesliga', country:'Alemanha', city:'Leverkusen', founded:1904, stadium:'BayArena', coach:'Erik ten Hag', color:'#E32219',
 titles:['1x Bundesliga (2023/24, invicto)','1x Copa da Alemanha'],
 legends:['Michael Ballack','Stefan Kießling'],
 squad:['Patrik Schick','Florian Wirtz? (transferido em 2025)','Granit Xhaka? (Sunderland)'],
 formation:'4-2-3-1', lines:[['Hradecky'],['Tapsoba','Tah','Hincapié','Grimaldo'],['Palacios','Andrich'],['Adli','Terrier','Poku'],['Schick']]},

{id:'freiburg', name:'SC Freiburg', league:'bundesliga', country:'Alemanha', city:'Friburgo', founded:1904, stadium:'Europa-Park Stadion', coach:'Julian Schuster', color:'#EC1C24',
 titles:['Referência alemã em formação de jovens e gestão de clube'],
 legends:['Volker Finke (técnico histórico)'],
 squad:['Vincenzo Grifo','Ritsu Doan'],
 formation:'4-2-3-1', lines:[['Atubolu'],['Günter','Ginter','Lienhart','Rosenfelder'],['Eggestein','Höfler'],['Doan','Grifo','Adamu'],['Höler']]},

{id:'frankfurt', name:'Eintracht Frankfurt', league:'bundesliga', country:'Alemanha', city:'Frankfurt', founded:1899, stadium:'Deutsche Bank Park', coach:'Dino Toppmöller', color:'#E1000F',
 titles:['1x Europa League (2021/22)','5x Copa da Alemanha'],
 legends:['Jean-Marie Pfaff','Andreas Möller'],
 squad:['Omar Marmoush? (transferido em 2025)','Hugo Ekitiké','Kevin Trapp'],
 formation:'3-4-2-1', lines:[['Trapp'],['Koch','Tuta','Theate'],['Chaibi','Larsson','Skhiri','Brown'],['Bahoya','Doan'],['Ekitiké']]},

{id:'augsburg', name:'FC Augsburg', league:'bundesliga', country:'Alemanha', city:'Augsburgo', founded:1907, stadium:'WWK Arena', coach:'Sandro Wagner', color:'#BA3733',
 titles:['Clube consolidado no meio de tabela da Bundesliga'],
 legends:['Daniel Baier'],
 squad:['Phillip Tietz','Elvis Rexhbeçaj'],
 formation:'4-2-3-1', lines:[['Dahmen'],['Gouweleeuw','Uduokhai','Giannoulis','Bauer'],['Rexhbeçaj','Maier'],['Engelhardt','Rieder','Wintzheimer'],['Tietz']]},

{id:'mainz', name:'Mainz 05', league:'bundesliga', country:'Alemanha', city:'Mainz', founded:1905, stadium:'MEWA Arena', coach:'Bo Henriksen', color:'#C3141E',
 titles:['Conhecido por revelar treinadores (Jürgen Klopp, Thomas Tuchel)'],
 legends:['Jürgen Klopp (técnico histórico)'],
 squad:['Jonathan Burkardt','Nadiem Amiri'],
 formation:'3-4-2-1', lines:[['Zentner'],['Bell','Hanche-Olsen','Caci'],['Sano','Amiri','Barreiro','Widmer'],['Nebel','Burkardt'],['Ache']]},

{id:'union-berlin', name:'Union Berlin', league:'bundesliga', country:'Alemanha', city:'Berlim', founded:1966, stadium:'Stadion An der Alten Försterei', coach:'Steffen Baumgart', color:'#EB1923',
 titles:['Clube tradicional da antiga Alemanha Oriental, com torcida muito fiel'],
 legends:['Torsten Mattuschka'],
 squad:['Benedict Hollerbach','Ilyas Ansah'],
 formation:'3-5-2', lines:[['Rönnow'],['Doekhi','Leite','Diogo Leite'],['Trimmel','Haberer','Tousart','Gießelmann','Skarke'],['Hollerbach','Ansah']]},

{id:'gladbach', name:'Borussia Mönchengladbach', league:'bundesliga', country:'Alemanha', city:'Mönchengladbach', founded:1900, stadium:'Borussia-Park', coach:'Gerardo Seoane', color:'#00963F',
 titles:['5x Bundesliga','3x Copa da UEFA'],
 legends:['Günter Netzer','Jupp Heynckes'],
 squad:['Alassane Pléa','Franck Honorat'],
 formation:'4-2-3-1', lines:[['Nicolas'],['Scally','Friedrich','Elvedi','Ahmedhodžić'],['Weigl','Kleindienst'],['Honorat','Reitz','Wharton'],['Pléa']]},

{id:'hamburgo', name:'Hamburgo SV', league:'bundesliga', country:'Alemanha', city:'Hamburgo', founded:1887, stadium:'Volksparkstadion', coach:'Merlin Polzin', color:'#0C2340',
 titles:['6x Campeão alemão','3x Copa da Alemanha'],
 legends:['Uwe Seeler','Kevin Keegan (passagem marcante)'],
 squad:['Ransford Königsdörffer','Robert Glatzel'],
 formation:'4-2-3-1', lines:[['Heuer Fernandes'],['Dompé','Mikelbrencis','Riedel','Reis'],['Muheim','Königsdörffer'],['Selke','Bénes','Glatzel'],['Aygün']]},

{id:'koln', name:'FC Köln', league:'bundesliga', country:'Alemanha', city:'Colônia', founded:1948, stadium:'RheinEnergieStadion', coach:'Lukas Kwasniok', color:'#ED1C24',
 titles:['2x Campeão alemão','4x Copa da Alemanha'],
 legends:['Wolfgang Overath'],
 squad:['Said El Mala','Damion Downs'],
 formation:'4-2-3-1', lines:[['Schwäbe'],['Meyer','Schmitz','Huseinbašić','Ismail'],['Kainz','Kilian'],['El Mala','Downs','Sylla'],['Tigges']]},

{id:'werder-bremen', name:'Werder Bremen', league:'bundesliga', country:'Alemanha', city:'Bremen', founded:1899, stadium:'Weserstadion', coach:'Ole Werner? (verificar)', color:'#1D9053',
 titles:['4x Campeão alemão','6x Copa da Alemanha'],
 legends:['Miroslav Klose (formado no clube)'],
 squad:['Marvin Ducksch','Mitchell Weiser'],
 formation:'3-4-3', lines:[['Zetterer'],['Stark','Friedl','Bittencourt'],['Weiser','Stage','Njinmah','Jung'],['Ducksch','Burke','Grüll']]},

{id:'schalke', name:'Schalke 04', league:'bundesliga', country:'Alemanha', city:'Gelsenkirchen', founded:1904, stadium:'Veltins-Arena', coach:'Miron Muslić', color:'#004A9F',
 titles:['7x Campeão alemão','5x Copa da Alemanha'],
 legends:['Manuel Neuer (formado no clube)','Klaus Fischer'],
 squad:['Kenan Karaman','Bryan Lasme'],
 formation:'4-2-3-1', lines:[['Loric'],['Sompis','Krauß','Aydin','Ouedraogo'],['Bulut','Bukusu'],['Ouwejan','Karaman','Tempelmann'],['Lasme']]},

{id:'elversberg', name:'SV Elversberg', league:'bundesliga', country:'Alemanha', city:'Elversberg (Spiesen-Elversberg)', founded:1907, stadium:'Ursapharm-Arena', coach:'Horst Steffen', color:'#000000',
 titles:['Acesso inédito à Bundesliga na sua história'],
 legends:['Clube revelação da temporada de acesso'],
 squad:['Elde Emberegos Semedo','Kai Brünker'],
 formation:'3-4-3', lines:[['Kittel'],['Hadžikadunić','Adamczyk','Kammerbauer'],['Correia','Bähre','Kircher','Kastenmeier'],['Brünker','Neubauer','Semedo']]},

{id:'paderborn', name:'SC Paderborn 07', league:'bundesliga', country:'Alemanha', city:'Paderborn', founded:1907, stadium:'Home Deluxe Arena', coach:'Lukas Kwasniok? (verificar)', color:'#003399',
 titles:['Acesso à Bundesliga via campanha de acesso 2025/26'],
 legends:['Clube conhecido por revelar jovens talentos alemães'],
 squad:['Adrian Ivanušec','Julian Justvan'],
 formation:'4-1-4-1', lines:[['Klaas'],['Schuster','Ansah','Gerlach','Conteh'],['Justvan'],['Ivanušec','Michel','Sarpei','Fassnacht'],['Krauße']]},

/* ===================== LIGUE 1 (França) ===================== */
{id:'psg', name:'Paris Saint-Germain', league:'ligue1', country:'França', city:'Paris', founded:1970, stadium:'Parc des Princes', coach:'Luis Enrique', color:'#004170',
 titles:['1x Champions League (2024/25)','13x Ligue 1','15x Copa da França'],
 legends:['Zlatan Ibrahimović','Thiago Silva','Marco Verratti'],
 squad:['Ousmane Dembélé','Vitinha','Gianluigi Donnarumma'],
 formation:'4-3-3', lines:[['Donnarumma'],['Mendes','Pacho','Marquinhos','Hakimi'],['Vitinha','Zaïre-Emery','Ruiz'],['Dembélé','Barcola','Doué']]},

{id:'marselha', name:'Olympique de Marselha', league:'ligue1', country:'França', city:'Marselha', founded:1899, stadium:'Stade Vélodrome', coach:'Roberto De Zerbi', color:'#2FAEE0',
 titles:['1x Champions League (1992/93)','10x Ligue 1'],
 legends:['Didier Drogba','Jean-Pierre Papin'],
 squad:['Mason Greenwood','Pierre-Emerick Aubameyang'],
 formation:'4-3-3', lines:[['Rulli'],['Nadir','Balerdi','Medina','Murillo'],['Höjbjerg','Bilal','Vermeeren'],['Greenwood','Aubameyang','O\'Riley']]},

{id:'lyon', name:'Olympique Lyonnais', league:'ligue1', country:'França', city:'Lyon', founded:1950, stadium:'Groupama Stadium', coach:'Paulo Fonseca', color:'#C8102E',
 titles:['7x Ligue 1 (sequência histórica 2002-2008)'],
 legends:['Juninho Pernambucano','Karim Benzema'],
 squad:['Rayan Cherki? (transferido em 2025)','Alexandre Lacazette','Corentin Tolisso'],
 formation:'4-2-3-1', lines:[['Lopes'],['Kluivert','Niakhaté','Mata','Tagliafico'],['Tolisso','Lepenant'],['Fofana','Karabec','Satriano'],['Lacazette']]},

{id:'monaco', name:'AS Monaco', league:'ligue1', country:'França', city:'Mônaco', founded:1924, stadium:'Stade Louis II', coach:'Adi Hütter', color:'#DD0A34',
 titles:['8x Ligue 1','5x Copa da França'],
 legends:['Thierry Henry (formado no clube)'],
 squad:['Wilfried Singo','Takumi Minamino','Maghnes Akliouche'],
 formation:'4-2-3-1', lines:[['Köhn'],['Singo','Salisu','Kehrer','Vanderson'],['Zakaria','Camara'],['Minamino','Akliouche','Ben Seghir'],['Balogun']]},

{id:'lille', name:'LOSC Lille', league:'ligue1', country:'França', city:'Lille', founded:1944, stadium:'Stade Pierre-Mauroy', coach:'Bruno Genesio', color:'#DA1F26',
 titles:['4x Ligue 1','6x Copa da França'],
 legends:['Eden Hazard (formado no clube)'],
 squad:['Jonathan David? (saiu em 2025)','Edon Zhegrova','Berke Özer'],
 formation:'4-2-3-1', lines:[['Özer'],['Meunier','Alexsandro','Diakité','Gudmundsson'],['André','Cabella'],['Zhegrova','Haraldsson','Sahraoui'],['Igamane']]},

{id:'nice', name:'OGC Nice', league:'ligue1', country:'França', city:'Nice', founded:1904, stadium:'Allianz Riviera', coach:'Franck Haise', color:'#CB1E30',
 titles:['4x Ligue 1'],
 legends:['Didier Digard (ex-jogador e técnico)'],
 squad:['Evann Guessand? (saiu em 2025)','Terem Moffi','Marcin Bułka'],
 formation:'4-3-3', lines:[['Bułka'],['Bard','Bah','Dante','Abdi'],['Boga','Vanhoutte','Sanson'],['Moffi','Diop','Louchet']]},

{id:'rennes', name:'Stade Rennais', league:'ligue1', country:'França', city:'Rennes', founded:1901, stadium:'Roazhon Park', coach:'Habib Beye', color:'#E2001A',
 titles:['1x Copa da França (2018/19)'],
 legends:['Petr Čech (formado no clube)'],
 squad:['Amine Gouiri','Ludovic Blas'],
 formation:'4-2-3-1', lines:[['Samba'],['Rouault','Wooh','Jacquet','Meïté'],['Fofana','Assignon'],['Blas','Gouiri','Kalimuendo'],['Kalimuendo']]},

{id:'strasbourg', name:'RC Strasbourg', league:'ligue1', country:'França', city:'Strasbourg', founded:1906, stadium:'Stade de la Meinau', coach:'Liam Rosenior', color:'#0072BB',
 titles:['2x Ligue 1 (histórico)','3x Copa da França'],
 legends:['Raymond Kopa (passagem marcante)'],
 squad:['Emanuel Emegha? (saiu em 2025)','Dilane Bakwa? (saiu em 2025)','Sebastian Nanasi'],
 formation:'4-3-3', lines:[['Penders'],['Sylla','Nyamsi','Perrin','Doué'],['Santos','Diarra','Barco'],['Nanasi','Moreira','Bakwa']]},

{id:'lens', name:'RC Lens', league:'ligue1', country:'França', city:'Lens', founded:1906, stadium:'Stade Bollaert-Delelis', coach:'Will Still', color:'#FFD200',
 titles:['1x Ligue 1 (1997/98)'],
 legends:['Marc-Vivien Foé'],
 squad:['Elye Wahi? (saiu em 2025)','Adrien Thomasson'],
 formation:'3-4-3', lines:[['Risser'],['Gradit','Danso','Medina'],['Machado','Sotoca','Thomasson','Pereira'],['Fulgini','Saïd','Sotoca']]},

{id:'toulouse', name:'Toulouse FC', league:'ligue1', country:'França', city:'Toulouse', founded:1970, stadium:'Stadium de Toulouse', coach:'Carles Martínez', color:'#611A34',
 titles:['1x Copa da França (1957)'],
 legends:['Étienne Mattler'],
 squad:['Thijs Dallinga? (saiu em 2025)','Aron Dønnum'],
 formation:'3-4-3', lines:[['Restes'],['Rasmussen','Nicolaisen','Diarra'],['Sidibé','Spierings','Casseres','Suazo'],['Dønnum','Magri','Ratão']]},

{id:'nantes', name:'FC Nantes', league:'ligue1', country:'França', city:'Nantes', founded:1943, stadium:'Stade de la Beaujoire', coach:'Luís Castro', color:'#FFD100',
 titles:['8x Ligue 1','3x Copa da França'],
 legends:['Marcelo Bielsa (técnico histórico)'],
 squad:['Mostafa Mohamed','Moses Simon'],
 formation:'4-2-3-1', lines:[['Descamps'],['Corchia','Kabore','Centonze','Amian'],['Sissoko','Abline'],['Simon','Mohamed','Coco'],['Mohamed']]},

{id:'montpellier', name:'Montpellier HSC', league:'ligue1', country:'França', city:'Montpellier', founded:1919, stadium:'Stade de la Mosson', coach:'Michel Der Zakarian', color:'#004C97',
 titles:['1x Ligue 1 (2011/12)','1x Copa da França'],
 legends:['Olivier Giroud (formado no clube)'],
 squad:['Arnaud Nordin','Khalil Fayad'],
 formation:'4-3-3', lines:[['Lecomte'],['Sambia','Mendes','Van den Boomen','Ferri'],['Chotard','Nordin','Ferri'],['Fayad','Wahi','Swiderski']]},

{id:'brest', name:'Stade Brestois', league:'ligue1', country:'França', city:'Brest', founded:1950, stadium:'Stade Francis-Le Blé', coach:'Eric Roy', color:'#DA291C',
 titles:['Melhor campanha histórica: fase de liga da Champions League 2024/25'],
 legends:['Campanha europeia inédita em 2024/25'],
 squad:['Romain Del Castillo','Ludovic Ajorque'],
 formation:'3-4-2-1', lines:[['Bizot'],['Chardonnet','Le Bihan','Doumbia'],['Lala','Magnetti','Belkhdim','Locko'],['Del Castillo','Sima'],['Ajorque']]},

{id:'lorient', name:'FC Lorient', league:'ligue1', country:'França', city:'Lorient', founded:1926, stadium:'Stade du Moustoir', coach:'Olivier Pantaloni', color:'#F47920',
 titles:['1x Copa da França (2001/02)'],
 legends:['Christophe Le Roux'],
 squad:['Igor Silva','Bamba Dang'],
 formation:'4-2-3-1', lines:[['Mannone'],['Le Goff','Talbi','Makengo','Fofana'],['Makhloufi','Abergel'],['Dang','Silva','Doucouré'],['Ouattara']]},

{id:'auxerre', name:'AJ Auxerre', league:'ligue1', country:'França', city:'Auxerre', founded:1905, stadium:'Stade Abbé-Deschamps', coach:'Christophe Pélissier', color:'#1C3F94',
 titles:['1x Ligue 1 (1995/96)','4x Copa da França'],
 legends:['Guy Roux (técnico histórico, quase 45 anos no cargo)'],
 squad:['Gauthier Hein','Lassine Sinayoko'],
 formation:'4-3-3', lines:[['Léon'],['Hunou','Mensah','Costil','Charles-Cook'],['Perrin','Autret','Elisor'],['Hein','Sinayoko','Danois']]},

{id:'le-havre', name:'Le Havre AC', league:'ligue1', country:'França', city:'Le Havre', founded:1872, stadium:'Stade Océane', coach:'Didier Digard', color:'#00549F',
 titles:['Clube de futebol mais antigo da França (fundado em 1872)'],
 legends:['Jules Bocandé'],
 squad:['Josué Casimir','Abdoulaye Touré'],
 formation:'4-3-3', lines:[['Mvogo'],['Ba','Sangante','Kitala','Fortune'],['Doucet','Touré','Ekomie'],['Casimir','Soumano','Bahi']]},

{id:'metz', name:'FC Metz', league:'ligue1', country:'França', city:'Metz', founded:1932, stadium:'Stade Saint-Symphorien', coach:'Stéphane Le Mignan', color:'#800000',
 titles:['2x Copa da França','2x Copa da Liga Francesa'],
 legends:['Robert Pirès (formado no clube)'],
 squad:['Georges Mikautadze? (saiu em 2025)','Cheikh Sabaly'],
 formation:'4-2-3-1', lines:[['Oukidja'],['Sadaoui','Traoré','Kouyaté','Wahi'],['Kadiri','Mikautadze'],['Sabaly','Yasser','Doury'],['Camara']]},

{id:'saint-etienne', name:'AS Saint-Étienne', league:'ligue1', country:'França', city:'Saint-Étienne', founded:1919, stadium:'Stade Geoffroy-Guichard', coach:'Eirik Horneland', color:'#005C34',
 titles:['10x Ligue 1 — maior campeão francês da história','6x Copa da França'],
 legends:['Michel Platini','Dominique Rocheteau'],
 squad:['Zuriko Davitashvili','Ibrahim Sissoko'],
 formation:'4-2-3-1', lines:[['Larsonneur'],['Fofana','Nadé','Batubinsika','Bernauer'],['Cornud','Bouchouari'],['Davitashvili','Ben Old','Sissoko'],['Stassin']]},

/* ===================== BRASILEIRÃO SÉRIE A (Brasil) ===================== */
{id:'athletico-pr', name:'Athletico Paranaense', league:'brasileirao', country:'Brasil', city:'Curitiba', founded:1924, stadium:'Ligga Arena (Arena da Baixada)', coach:'Odair Hellmann', color:'#B21F24',
 titles:['2x Copa Sul-Americana','1x Copa Libertadores? (finalista em 2005, 2022)'],
 legends:['Kléberson','Alex'],
 squad:['Julimar','Mastriani'],
 formation:'4-3-3', lines:[['Léo Linck'],['Esquivel','Zapelli','Thiago Heleno','Villalba'],['Fernandinho','Christian','Zapelli'],['Julimar','Mastriani','Alex Santana']]},

{id:'atletico-mg', name:'Atlético Mineiro', league:'brasileirao', country:'Brasil', city:'Belo Horizonte', founded:1908, stadium:'Arena MRV', coach:'Cuca', color:'#000000',
 titles:['1x Copa Libertadores (2013)','2x Brasileirão'],
 legends:['Reinaldo','Dodô','Ronaldinho Gaúcho (passagem marcante)'],
 squad:['Hulk','Paulinho','Everson'],
 formation:'4-2-3-1', lines:[['Everson'],['Guilherme Arana','Lyanco','Alonso','Mariano'],['Alan Franco','Otávio'],['Paulinho','Rony','Alan Kardec'],['Hulk']]},

{id:'bahia', name:'Bahia', league:'brasileirao', country:'Brasil', city:'Salvador', founded:1931, stadium:'Arena Fonte Nova', coach:'Rogério Ceni', color:'#004791',
 titles:['2x Brasileirão','1x Copa do Brasil'],
 legends:['Bobô','Cléo'],
 squad:['Everaldo','Erick Pulga'],
 formation:'4-2-3-1', lines:[['Marcos Felipe'],['Gilberto','Kanu','Victor Cuesta','Ryan'],['Jean Lucas','Jota Silva'],['Erick Pulga','Cauly','Ademir'],['Everaldo']]},

{id:'botafogo', name:'Botafogo', league:'brasileirao', country:'Brasil', city:'Rio de Janeiro', founded:1904, stadium:'Estádio Nilton Santos (mandante)', coach:'Davide Ancelotti', color:'#000000',
 titles:['1x Copa Libertadores (2024)','1x Mundial de Clubes (2024)','2x Brasileirão recentes'],
 legends:['Garrincha','Nilton Santos'],
 squad:['Igor Jesus? (transferido em 2025)','Savarino','John'],
 formation:'4-3-3', lines:[['John'],['Vitinho','Alexander Barboza','Bastos','Alex Telles'],['Marlon Freitas','Danilo Barbosa','Newton'],['Savarino','Chris Ramos','Artur']]},

{id:'chapecoense', name:'Chapecoense', league:'brasileirao', country:'Brasil', city:'Chapecó', founded:1973, stadium:'Arena Condá', coach:'Eduardo Baptista', color:'#00693C',
 titles:['1x Copa Sul-Americana (2016/17, título póstumo à tragédia aérea)'],
 legends:['Elenco de 2016, homenageado mundialmente'],
 squad:['Rafael Elias','Kaio Nunes'],
 formation:'4-3-3', lines:[['Gustavo'],['Diego Ivo','Kanu','Reginaldo','Rafael Bilu'],['Jaminton Campaz','Denner','Willyan'],['Rafael Elias','Kaio Nunes','Perotti']]},

{id:'corinthians', name:'Corinthians', league:'brasileirao', country:'Brasil', city:'São Paulo', founded:1910, stadium:'Neo Química Arena', coach:'Dorival Júnior', color:'#000000',
 titles:['2x Mundial de Clubes','7x Brasileirão','3x Copa Libertadores'],
 legends:['Sócrates','Rivelino'],
 squad:['Yuri Alberto','Memphis Depay','Hugo Souza'],
 formation:'4-2-3-1', lines:[['Hugo Souza'],['Matheuzinho','Félix Torres','Gustavo Henrique','Hugo'],['Raniele','Charles'],['Depay','Rodrigo Garro','Talles Magno'],['Yuri Alberto']]},

{id:'coritiba', name:'Coritiba', league:'brasileirao', country:'Brasil', city:'Curitiba', founded:1909, stadium:'Estádio Couto Pereira', coach:'Mozart', color:'#00833E',
 titles:['1x Copa do Brasil (1995)','7x Campeonato Paranaense (destaque estadual)'],
 legends:['Alex (formado no clube)'],
 squad:['Gabriel Silva','Natanael'],
 formation:'4-3-3', lines:[['Pedro Rocha'],['Natanael','Fabrício Domínguez','Zeca','Matheus Alexandre'],['William Farias','Dudu','Bruno Gomes'],['Gabriel Silva','Bento','Zé Vitor']]},

{id:'cruzeiro', name:'Cruzeiro', league:'brasileirao', country:'Brasil', city:'Belo Horizonte', founded:1921, stadium:'Estádio Mineirão (mandante)', coach:'Leonardo Jardim', color:'#00549F',
 titles:['4x Brasileirão','2x Copa Libertadores'],
 legends:['Tostão','Dirceu Lopes'],
 squad:['Kaio Jorge','Matheus Pereira','Cássio'],
 formation:'4-2-3-1', lines:[['Cássio'],['William','João Marcelo','Zé Ivaldo','Fagner'],['Lucas Silva','Matheus Henrique'],['Matheus Pereira','Sinisterra','Christian'],['Kaio Jorge']]},

{id:'flamengo', name:'Flamengo', league:'brasileirao', country:'Brasil', city:'Rio de Janeiro', founded:1895, stadium:'Maracanã (mandante)', coach:'Filipe Luís', color:'#C1272D',
 titles:['3x Copa Libertadores','8x Brasileirão','1x Mundial de Clubes'],
 legends:['Zico','Júnior','Zagallo'],
 squad:['Gerson','Bruno Henrique','Rossi'],
 formation:'4-3-3', lines:[['Rossi'],['Ayrton Lucas','Léo Pereira','Danilo','Wesley'],['Erick Pulgar','Gerson','Arrascaeta'],['Bruno Henrique','Pedro','Luiz Araújo']]},

{id:'fluminense', name:'Fluminense', league:'brasileirao', country:'Brasil', city:'Rio de Janeiro', founded:1902, stadium:'Estádio Maracanã (mandante)', coach:'Renato Gaúcho', color:'#830619',
 titles:['1x Copa Libertadores (2023)','4x Brasileirão'],
 legends:['Rivellino','Telê Santana'],
 squad:['Germán Cano','Everaldo','Fábio'],
 formation:'4-2-3-1', lines:[['Fábio'],['Samuel Xavier','Thiago Silva','Ignácio','Renê'],['Martinelli','Nonato'],['Everaldo','Lima','Keno'],['Cano']]},

{id:'gremio', name:'Grêmio', league:'brasileirao', country:'Brasil', city:'Porto Alegre', founded:1903, stadium:'Arena do Grêmio', coach:'Mano Menezes', color:'#00A9E0',
 titles:['1x Mundial de Clubes (1983)','2x Copa Libertadores','5x Brasileirão'],
 legends:['Renato Gaúcho (ex-jogador)','Ronaldinho Gaúcho (formado no clube)'],
 squad:['Braithwaite','Cristaldo'],
 formation:'4-2-3-1', lines:[['Tiago Volpi'],['João Pedro','Kannemann','Rodrigo Ely','Marlon'],['Dodi','Villasanti'],['Cristaldo','Edenilson','Aravena'],['Braithwaite']]},

{id:'internacional', name:'Internacional', league:'brasileirao', country:'Brasil', city:'Porto Alegre', founded:1909, stadium:'Estádio Beira-Rio', coach:'Roger Machado', color:'#E30613',
 titles:['2x Mundial de Clubes','2x Copa Libertadores','3x Brasileirão'],
 legends:['Falcão','Dunga'],
 squad:['Alan Patrick','Enner Valencia'],
 formation:'4-2-3-1', lines:[['Rochet'],['Bustos','Vitão','Mercado','Bernabei'],['Bruno Henrique','Fernando'],['Alan Patrick','Wesley','Borré'],['Valencia']]},

{id:'mirassol', name:'Mirassol', league:'brasileirao', country:'Brasil', city:'Mirassol (SP)', founded:1925, stadium:'Estádio Municipal José Maria de Campos Maia', coach:'Rafael Guanaes', color:'#F7A81B',
 titles:['1x Acesso histórico à Série A em 2025'],
 legends:['Clube revelação recente do interior paulista'],
 squad:['Negueba','Iury Castilho'],
 formation:'4-2-3-1', lines:[['Alex Muralha'],['Reinaldo','Danielzinho','Alan Empereur','Índio'],['Neto Moura','Aylon'],['Negueba','Cristian','Edson Carioca'],['Iury Castilho']]},

{id:'palmeiras', name:'Palmeiras', league:'brasileirao', country:'Brasil', city:'São Paulo', founded:1914, stadium:'Allianz Parque', coach:'Abel Ferreira', color:'#006437',
 titles:['3x Copa Libertadores','12x Brasileirão','1x Recopa Sul-Americana'],
 legends:['Ademir da Guia','Rivaldo'],
 squad:['Estêvão','Raphael Veiga','Weverton'],
 formation:'4-2-3-1', lines:[['Weverton'],['Piquerez','Gómez','Murilo','Mayke'],['Aníbal Moreno','Richard Ríos'],['Raphael Veiga','Flaco López','Estêvão']]},

{id:'bragantino', name:'Red Bull Bragantino', league:'brasileirao', country:'Brasil', city:'Bragança Paulista', founded:1928, stadium:'Estádio Nabi Abi Chedid', coach:'Fernando Seabra', color:'#FFFFFF',
 titles:['Consolidado na elite após reformulação e investimento do grupo Red Bull'],
 legends:['Base histórica como Clube Atlético Bragantino'],
 squad:['Eduardo Sasha','Lucas Evangelista'],
 formation:'4-2-3-1', lines:[['Cleiton'],['Juninho','Alix Vinícius','Léo Ortiz','Escobar'],['Raul','Eric Ramires'],['Lucas Evangelista','Praxedes','Sasha'],['Ytalo']]},

{id:'remo', name:'Clube do Remo', league:'brasileirao', country:'Brasil', city:'Belém', founded:1905, stadium:'Estádio Baenão / Mangueirão', coach:'Rodrigo Santana', color:'#005CA9',
 titles:['1x Acesso histórico à Série A'],
 legends:['Maior torcida do futebol paraense'],
 squad:['Marcos Vinícius','Pedro Rocha'],
 formation:'4-3-3', lines:[['Vinícius'],['Marlon','Marcelo','Marcos Vinícius','Igor Fernandes'],['Nicolas','Lucas Freitas','Erick'],['Pedro Rocha','Ronald','Janeudo']]},

{id:'santos', name:'Santos', league:'brasileirao', country:'Brasil', city:'Santos', founded:1912, stadium:'Vila Belmiro', coach:'César Sampaio', color:'#000000',
 titles:['1x Mundial de Clubes (era Pelé)','8x Brasileirão'],
 legends:['Pelé','Neymar (formado no clube)'],
 squad:['Guilherme','Neymar? (retorno especulado)'],
 formation:'4-2-3-1', lines:[['Gabriel Brazão'],['Escobar','Zé Ivaldo','Rincón','Souza'],['Diego Pituca','Tomás Rincón'],['Guilherme','Barreal','Deivid Washington'],['Tiquinho Soares']]},

{id:'sao-paulo', name:'São Paulo', league:'brasileirao', country:'Brasil', city:'São Paulo', founded:1930, stadium:'MorumBIS', coach:'Hernán Crespo', color:'#FE0000',
 titles:['3x Mundial de Clubes','3x Copa Libertadores','6x Brasileirão'],
 legends:['Raí','Rogério Ceni'],
 squad:['Lucas Moura','André Silva','Rafael'],
 formation:'4-2-3-1', lines:[['Rafael'],['Igor Vinícius','Arboleda','Sabino','Welington'],['Alisson','Pablo Maia'],['Lucas Moura','Lucas','Ferreira'],['André Silva']]},

{id:'vasco', name:'Vasco da Gama', league:'brasileirao', country:'Brasil', city:'Rio de Janeiro', founded:1898, stadium:'Estádio São Januário (mandante)', coach:'Fernando Diniz', color:'#000000',
 titles:['4x Brasileirão','1x Copa Libertadores (1998)'],
 legends:['Roberto Dinamite','Romário (passagem marcante)'],
 squad:['Vegetti','Philippe Coutinho'],
 formation:'4-2-3-1', lines:[['Léo Jardim'],['Paulo Henrique','João Victor','Lucas Freitas','Alan Ferreira'],['Hugo Moura','Sforza'],['Coutinho','Rayan','Nuno Moreira'],['Vegetti']]},

{id:'vitoria', name:'Vitória', league:'brasileirao', country:'Brasil', city:'Salvador', founded:1899, stadium:'Estádio Manoel Barradas (Barradão)', coach:'Thiago Carpini', color:'#E4020F',
 titles:['Clube tradicional baiano, rival histórico do Bahia'],
 legends:['Bebeto (formado no clube)'],
 squad:['Osvaldo','Renato Kayzer'],
 formation:'4-3-3', lines:[['Lucas Arcanjo'],['Camutanga','Wagner Leonardo','Reynaldo','Alisson Farias'],['Willian Oliveira','Léo Naldi','Vico'],['Osvaldo','Renato Kayzer','Matheusinho']]},

];
